name: Swift CI
run-name: Build smoke test by ${{ github.actor }}

on: [push, pull_request]

jobs:
  test:
    name: Test UIDeviceComplete
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test (iOS)
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "UIDeviceComplete.xcodeproj" -scheme "UIDeviceComplete" -destination "generic/platform=iOS Simulator" clean test | xcpretty
    - name: Test (watchOS)
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "UIDeviceComplete.xcodeproj" -scheme "UIDeviceComplete" -destination "generic/platform=watchOS Simulator" clean test | xcpretty
